# Generated by Django 5.0.4 on 2024-04-20 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("resumes", "0001_initial"),
        ("resumes", "0002_rename_code_currency_name"),
        ("resumes", "0003_resume_api_id"),
        ("resumes", "0004_alter_applicant_area_alter_resume_created_at_and_more"),
        ("resumes", "0005_alter_applicant_gender"),
        ("resumes", "0006_alter_applicant_gender"),
        ("resumes", "0007_alter_education_primary_name"),
        ("resumes", "0008_alter_education_primary_result_and_more"),
        ("resumes", "0009_alter_education_primary_organization"),
        ("resumes", "0010_alter_resume_description"),
        ("resumes", "0011_alter_applicant_age_alter_applicant_area_and_more"),
        ("resumes", "0012_alter_applicant_gender"),
        ("resumes", "0013_alter_experienceindustry_name"),
        ("resumes", "0014_alter_experienceindustry_name"),
        ("resumes", "0015_folder"),
        ("resumes", "0016_resume_invite"),
        ("resumes", "0017_resume_delete_resume_keep"),
        ("resumes", "0018_rename_keep_resume_favorite"),
        ("resumes", "0019_auto_20240420_0559"),
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name="EducationLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ExperienceIndustry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="-", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ExperiencePosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Applicant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255, null=True)),
                ("last_name", models.CharField(max_length=255, null=True)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("age", models.PositiveIntegerField(null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Мужчина", "Мужчина"),
                            ("Женщина", "Женщина"),
                            ("Не указан", "Не указан"),
                        ],
                        default="Мужчина",
                        max_length=15,
                        null=True,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("total_experience", models.PositiveIntegerField(null=True)),
                ("area", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("primary_name", models.CharField(max_length=255, null=True)),
                ("primary_organization", models.CharField(max_length=255, null=True)),
                ("primary_result", models.CharField(max_length=255, null=True)),
                ("primary_year", models.PositiveIntegerField(null=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="educations",
                        to="resumes.applicant",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="resumes.educationlevel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=255, null=True)),
                ("start", models.DateField(null=True)),
                ("end", models.DateField(null=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiences",
                        to="resumes.applicant",
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="resumes.area",
                    ),
                ),
                (
                    "industry",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="resumes.experienceindustry",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="resumes.experienceposition",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("certificate", models.URLField(blank=True, null=True)),
                ("salary_amount", models.PositiveIntegerField(null=True)),
                ("title", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("description", models.CharField(max_length=2048, null=True)),
                (
                    "applicant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resumes.applicant",
                    ),
                ),
                (
                    "salary_currency",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="resumes.currency",
                    ),
                ),
                ("api_id", models.IntegerField(default=1, unique=True)),
                ("invite", models.BooleanField(default=False)),
                ("delete", models.BooleanField(default=False)),
                ("favorite", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Folder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("date_create", models.DateField(auto_now=True)),
                ("resumes", models.ManyToManyField(to="resumes.resume")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
