# Generated by Django 5.0.4 on 2024-04-19 08:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resumes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="currency",
            old_name="code",
            new_name="name",
        ),
    ]
