# Generated by Django 5.0.4 on 2024-04-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resumes", "0004_alter_applicant_area_alter_resume_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="gender",
            field=models.CharField(
                choices=[("Мужской", "Мужской"), ("Мужской", "Женский")],
                default="Мужской",
                max_length=15,
            ),
        ),
    ]
