# Generated by Django 5.0.4 on 2024-04-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resumes", "0005_alter_applicant_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="gender",
            field=models.CharField(
                choices=[
                    ("Мужской", "Мужской"),
                    ("Женский", "Женский"),
                    ("Не указан", "Не указан"),
                ],
                default="Мужской",
                max_length=15,
            ),
        ),
    ]
