# Generated by Django 5.0.4 on 2024-04-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resumes", "0008_alter_education_primary_result_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="primary_organization",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
