# Generated by Django 5.0.4 on 2024-04-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resumes", "0009_alter_education_primary_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="description",
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
