# Generated by Django 5.0.4 on 2024-04-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resumes", "0010_alter_resume_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="age",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="area",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="first_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="last_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="total_experience",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="experience",
            name="company",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="experience",
            name="end",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="experience",
            name="start",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="resume",
            name="salary_amount",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
