# Generated by Django 5.0.4 on 2024-04-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resumes", "0011_alter_applicant_age_alter_applicant_area_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="gender",
            field=models.CharField(
                choices=[
                    ("Мужчина", "Мужчина"),
                    ("Женщина", "Женщина"),
                    ("Не указан", "Не указан"),
                ],
                default="Мужчина",
                max_length=15,
                null=True,
            ),
        ),
    ]
