# Generated by Django 5.0.4 on 2024-04-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resumes", "0012_alter_applicant_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experienceindustry",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
