# Generated by Django 5.0.4 on 2024-04-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resumes", "0015_folder"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="invite",
            field=models.BooleanField(default=False),
        ),
    ]
