# Generated by Django 5.0.4 on 2024-04-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resumes", "0016_resume_invite"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="resume",
            name="keep",
            field=models.BooleanField(default=False),
        ),
    ]
