# Generated by Django 5.0.4 on 2024-04-19 21:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resumes", "0017_resume_delete_resume_keep"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resume",
            old_name="keep",
            new_name="favorite",
        ),
    ]
