# Generated by Django 5.0.4 on 2024-04-20 01:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resumes", "0001_initial_squashed_0019_auto_20240420_0559"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experienceindustry",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="resume",
            name="api_id",
            field=models.IntegerField(unique=True),
        ),
    ]
